from enum import StrEnum


class MarketEventType(StrEnum):
    MARKET_SNAPSHOT = "MARKET_SNAPSHOT"
    TICKER = "TICKER"
    TRADE = "TRADE"
    ORDERBOOK_SNAPSHOT = "ORDERBOOK_SNAPSHOT"
    ORDERBOOK_DELTA = "ORDERBOOK_DELTA"
    LIFECYCLE = "LIFECYCLE"


class MarketHealth(StrEnum):
    WARMING_UP = "WARMING_UP"
    LIVE = "LIVE"
    STALE = "STALE"
    RECOVERING = "RECOVERING"
    INVALID = "INVALID"


class IncidentType(StrEnum):
    PRICE_SHOCK = "PRICE_SHOCK"
    VOLUME_SPIKE = "VOLUME_SPIKE"
    SPREAD_ANOMALY = "SPREAD_ANOMALY"
    ORDERBOOK_IMBALANCE = "ORDERBOOK_IMBALANCE"
    LIQUIDITY_SHOCK = "LIQUIDITY_SHOCK"
    CROSS_MARKET_DIVERGENCE = "CROSS_MARKET_DIVERGENCE"


class EvidenceKind(StrEnum):
    MARKET_DATA = "MARKET_DATA"
    CONTRACT_RULES = "CONTRACT_RULES"
    OFFICIAL_SOURCE = "OFFICIAL_SOURCE"
    NEWS = "NEWS"
    ANALYSIS = "ANALYSIS"


class InvestigationStatus(StrEnum):
    CREATED = "CREATED"
    PLANNING = "PLANNING"
    GATHERING_EVIDENCE = "GATHERING_EVIDENCE"
    TESTING_HYPOTHESES = "TESTING_HYPOTHESES"
    CRITIQUING = "CRITIQUING"
    REVISING = "REVISING"
    COMPLETED = "COMPLETED"
    INCONCLUSIVE = "INCONCLUSIVE"
    FAILED = "FAILED"


class HypothesisStatus(StrEnum):
    UNTESTED = "UNTESTED"
    SUPPORTED = "SUPPORTED"
    CONTRADICTED = "CONTRADICTED"
    INCONCLUSIVE = "INCONCLUSIVE"


class ClaimKind(StrEnum):
    FACT = "FACT"
    INFERENCE = "INFERENCE"
    SPECULATION = "SPECULATION"
